# Generated by Django 5.2.10 on 2026-05-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='donationtype',
            field=models.CharField(choices=[('animals', 'Animals'), ('none', 'None')], default='animals', max_length=20),
        ),
    ]
