# Generated by Django 5.2.10 on 2026-05-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_donorprofile_donationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
