# Generated by Django 5.2.10 on 2026-05-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_donorprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(blank=True, max_length=50)),
                ('staff_desg', models.CharField(blank=True, max_length=50)),
                ('staff_address', models.CharField(max_length=100)),
                ('staff_dob', models.DateField(blank=True, null=True)),
                ('staff_Location', models.CharField(blank=True, max_length=30)),
                ('staff_contact', models.CharField(blank=True, max_length=15)),
                ('staff_mail', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
