# Generated by Django 5.2.10 on 2026-05-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_staffprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='staff'),
        ),
    ]
