# Generated by Django 5.2.10 on 2026-05-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_staffprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='donationtype',
        ),
    ]
