# Generated by Django 5.2.10 on 2026-05-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='type',
            field=models.CharField(choices=[('user', 'User Complaint'), ('staff', 'Staff Complaint')], default='user', max_length=10),
        ),
    ]
