# Generated by Django 5.2.10 on 2026-05-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_cart',
            new_name='Category_product',
        ),
    ]
