# Generated by Django 5.2.10 on 2026-05-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_ecommerce', '0002_rename_category_cart_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
