# Generated by Django 5.2.10 on 2026-05-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petoperation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='Pet_vaccinated',
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_vaccinated',
            field=models.BooleanField(default=False),
        ),
    ]
