# Generated by Django 4.2.4 on 2026-05-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petoperation', '0002_remove_pet_pet_vaccinated_pet_pet_vaccinated'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
