# Generated by Django 5.2.10 on 2026-05-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petoperation', '0007_alter_category_name_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
